<?php
declare(strict_types=1);

use Miklcct\ThinPhpApp\Demo\HelloView;
/** @var HelloView $this */
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Hello</title>
    </head>
    <body>
        <p>
            Hello World!
        </p>
        <p>
            The server time now is <?= e(strftime('%c')) ?>.
        </p>
        <p>
            You are visiting this page from IP address <?= e($this->ipAddress) ?>.
        </p>
    </body>
</html>