on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer validate
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: tar --xz -cf dependencies.tar.xz vendor composer.lock
      - uses: actions/upload-artifact@v1
        with:
          name: dependencies
          path: dependencies.tar.xz

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dependencies
      - run: tar --xz -xf dependencies.tar.xz
      - run: php vendor/bin/phpunit test

  phpstan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dependencies
      - run: tar --xz -xf dependencies.tar.xz
      - run: php vendor/bin/phpstan analyse src test
